#!/usr/bin/env bash
# Phase 7 Stage 0: Pre-flight checks (environment, paths, GPU).
#
# Run:
#   bash test/smoke/stage0_preflight.sh
# Or if on remote with sshfs paths:
#   NAVDSL_DATA_BASE=/home/hjk/sshfs_root/dataset/habitat-data bash test/smoke/stage0_preflight.sh
#
# Success criteria: every check prints OK. Any FAIL → fix before continuing.

set -u
cd "$(dirname "$0")/../.."  # cd to NavDSL repo root
source test/smoke/_paths.sh

echo ""
echo "=========================================="
echo "STAGE 0: Pre-flight checks"
echo "=========================================="

# --- 0.1 Python + critical deps ---
echo ""
echo "--- 0.1 Python + dependencies ---"
python -c "
import sys
print(f'Python: {sys.version}')
import torch, habitat, habitat_baselines, habitat_sim, lmdb, networkx, transformers, numpy
print(f'torch: {torch.__version__}')
print(f'CUDA available: {torch.cuda.is_available()}')
print(f'CUDA devices: {torch.cuda.device_count()}')
print(f'habitat_sim: {habitat_sim.__version__ if hasattr(habitat_sim, \"__version__\") else \"?\"}')
print(f'transformers: {transformers.__version__}')
print(f'lmdb: {lmdb.__version__}')
print(f'networkx: {networkx.__version__}')
print('DEPS_OK')
" || { echo "FAIL: dependencies"; exit 1; }

# --- 0.2 Data files exist ---
echo ""
echo "--- 0.2 Data files ---"
check_file() {
    local desc="$1" path="$2"
    echo "$desc : $path"
    if [ -e "$path" ]; then
        echo "  OK: $desc"
    else
        echo "  FAIL: $desc -> $path"
        return 1
    fi
}

FAIL=0
check_file "Episodes train json.gz" "$NAVDSL_EPISODES/train/train.json.gz" || FAIL=1
check_file "Episodes val json.gz"   "$NAVDSL_EPISODES/val/val.json.gz"   || FAIL=1
check_file "HM3D scenes dir"        "$NAVDSL_SCENES"                      || FAIL=1
check_file "Scene dataset config"   "$NAVDSL_SCENE_DATASET_CONFIG"        || FAIL=1
check_file "Nav graph dir"          "$NAVDSL_NAV_GRAPH"                   || FAIL=1
check_file "Rel angles json"        "$NAVDSL_REL_ANGLES"                  || FAIL=1
check_file "Pretrained DUET ckpt"   "$NAVDSL_DUET_CKPT"                   || FAIL=1
[ "$FAIL" = "1" ] && exit 1

# --- 0.3 Per-scan LMDB ---
echo ""
echo "--- 0.3 Per-scan LMDB (generated by split_lmdb_per_scan.py) ---"
TRAIN_N=$(ls "$NAVDSL_PER_SCAN/train/" 2>/dev/null | wc -l)
VAL_N=$(ls "$NAVDSL_PER_SCAN/val/" 2>/dev/null | wc -l)
echo "  per_scan/train: $TRAIN_N files (expected 800)"
echo "  per_scan/val:   $VAL_N files (expected 100)"

if [ "$TRAIN_N" -lt 800 ] || [ "$VAL_N" -lt 100 ]; then
    echo "  WARN: per-scan LMDB incomplete. Generate it via:"
    echo "    python -m navdsl.data_adapter.split_lmdb_per_scan \\"
    echo "        --source-view-lmdb $NAVDSL_DATA_BASE/datasets/vln/hm3d/autovln/v1.0/NAV_GRAPH/features/view_timm_imagenet_vitb16 \\"
    echo "        --source-obj-lmdb $NAVDSL_DATA_BASE/datasets/vln/hm3d/autovln/v1.0/NAV_GRAPH/features/obj2d_ade20k_pseudo3d_merged_timm_imagenet_vitb16 \\"
    echo "        --output-dir $NAVDSL_PER_SCAN"
    echo "  (~2 hours; one-time cost)"
    # Not failing — they may want to use legacy monolithic mode instead
fi

# --- 0.4 Smoke scene present ---
echo ""
echo "--- 0.4 Smoke scene in dataset ---"
if [ -d "$NAVDSL_SCENES/train/$NAVDSL_SMOKE_SCENE" ]; then
    echo "  OK: scene mesh at $NAVDSL_SCENES/train/$NAVDSL_SMOKE_SCENE/"
else
    echo "  FAIL: smoke scene not found"
    exit 1
fi

if [ -f "$NAVDSL_PER_SCAN/train/$NAVDSL_SMOKE_SCENE.lmdb" ]; then
    echo "  OK: per-scan LMDB at $NAVDSL_PER_SCAN/train/$NAVDSL_SMOKE_SCENE.lmdb"
else
    echo "  WARN: per-scan LMDB for smoke scene missing (will use zeros at runtime)"
fi

echo ""
echo "=========================================="
echo "STAGE 0 PASSED"
echo "=========================================="
